# Generated by Django 5.0.4 on 2024-06-17 11:06

import post.validatorFile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='studentCode',
            field=models.CharField(default=0, max_length=12, validators=[post.validatorFile.validate_No_Alphabet]),
        ),
    ]
