# Generated by Django 5.0.4 on 2024-06-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_imagecollection_post_imagecollections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imageCollections',
        ),
    ]
