# Generated by Django 5.0.4 on 2024-06-17 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_remove_post_imagecollections'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecollection',
            name='file',
            field=models.FileField(default='default.jpg', null=True, upload_to='media/test/'),
        ),
        migrations.AddField(
            model_name='imagecollection',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
