# Generated by Django 5.0.4 on 2024-07-11 06:29

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_rename_categories_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
