# Generated by Django 5.0.4 on 2024-07-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adminStutus',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='teacherStutus',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='response',
            new_name='title',
        ),
    ]
