# Generated by Django 5.0.4 on 2024-07-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_rename_vip_user_forumsmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=500),
        ),
    ]
