# Generated by Django 5.0.4 on 2024-07-19 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_alter_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='largeContent',
        ),
        migrations.CreateModel(
            name='largeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
    ]
